### ISSUE TITLE
Error in pyinterp.core when trying to import pyinterp on Windows

### ISSUE THREAD

**Issue by DManowitz** [CNES/pangeo-pyinterp#22]
**Describe the bug**
When trying to import pyinterp (v2023.2.1), I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\manow\miniconda3\envs\py38_ml_TfGpuMain\lib\site-packages\pyinterp\__init__.py", line 9, in <module>
    from . import geodetic, geohash, version
  File "C:\Users\manow\miniconda3\envs\py38_ml_TfGpuMain\lib\site-packages\pyinterp\geodetic\__init__.py", line 9, in <module>
    from .. import interface
  File "C:\Users\manow\miniconda3\envs\py38_ml_TfGpuMain\lib\site-packages\pyinterp\interface.py", line 14, in <module>
    from . import core
ImportError: DLL load failed while importing core: The specified module could not be found.
```

Looking at the `core.cp38-win_amd64.pyd` library with [Dependencies](https://github.com/lucasg/Dependencies), I see that the library is linked against `gsl-25.dll`.  However, the gsl (v2.7.1) library is just `gsl.dll`

**To Reproduce**
Install pyinterp=2023.2.1=mkl_py38hb2a16ad_0 via conda on Windows 10
`import pyinterp`

**Expected behavior**
No crash

**Pyinterp/Numpy/Python version information**
Output from
```python
import sys, numpy, pyinterp.version
print(pyinterp.__version__)
print(numpy.__version__)
print(sys.version)
```

pyinterp v2023.2.1
numpy v1.23.5
python v3.8.16 (default, Jan 17 2023, 22:25:28) [MSC v.1916 64 bit (AMD64)]

**Comment by fbriol** [comment]
The version of the compiler used by conda-forge on Windows has changed. I have rebuilt a new package ([in progress](https://github.com/conda-forge/pyinterp-feedstock/runs/13602958693)). Let me know if this solves your problem.

**Comment by DManowitz** [comment]
Actually, my last comment may be wrong.  I just noticed a newer package version on conda-forge.  I will try that now.

**Comment by DManowitz** [comment]
Just tried with version 2023.5.0=mkl_py38... on conda-forge and got the same error.  It appears that the gsl linkage issue is still present.

**Comment by DManowitz** [comment]
The problem is still present with version 2023.11.0=mkl_py38h484629e_0.
